export const COGNITO_INSTANCE_TOKEN = "COGNITO_INSTANCE_TOKEN";
export const COGNITO_CLIENT_INSTANCE_TOKEN = "COGNITO_CLIENT_INSTANCE_TOKEN";
export const COGNITO_MODULE_OPTIONS = "COGNITO_MODULE_OPTIONS";
