export const COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN =
  "COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN";

export const COGNITO_JWT_VERIFIER_INSTANCE_TOKEN =
  "COGNITO_JWT_VERIFIER_INSTANCE_TOKEN";

export const COGNITO_JWT_EXTRACTOR_INSTANCE_TOKEN =
  "COGNITO_JWT_EXTRACTOR_INSTANCE_TOKEN";

export const COGNITO_MODULE_OPTIONS = "COGNITO_MODULE_OPTIONS";
