export const COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN =
  "COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN";

export const COGNITO_IDENTITY_PROVIDER_CLIENT_INSTANCE_TOKEN =
  "COGNITO_IDENTITY_PROVIDER_CLIENT_INSTANCE_TOKEN";

export const COGNITO_JWT_VERIFIER_SINGLE_USER_POOL_INSTANCE_TOKEN =
  "COGNITO_JWT_VERIFIER_SINGLE_USER_POOL_INSTANCE_TOKEN";

export const COGNITO_JWT_VERIFIER_MULTI_USER_POOL_INSTANCE_TOKEN =
  "COGNITO_JWT_VERIFIER_MULTI_USER_POOL_INSTANCE_TOKEN";

export const COGNITO_MODULE_OPTIONS = "COGNITO_MODULE_OPTIONS";
