name: Coverage

on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BLUE_EMAIL: ${{ secrets.BLUE_EMAIL }}
  BLUE_PASSWORD: ${{ secrets.BLUE_PASSWORD }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
  COGNITO_USER_EMAIL: ${{ secrets.COGNITO_USER_EMAIL }}
  COGNITO_USER_EMAIL_ADMIN: ${{ secrets.COGNITO_USER_EMAIL_ADMIN }}
  COGNITO_USER_PASSWORD: ${{ secrets.COGNITO_USER_PASSWORD }}
  COGNITO_USER_PASSWORD_ADMIN: ${{ secrets.COGNITO_USER_PASSWORD_ADMIN }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  FLIPPER_EMAIL: ${{ secrets.FLIPPER_EMAIL }}
  FLIPPER_PASSWORD: ${{ secrets.FLIPPER_PASSWORD }}
  MOBY_EMAIL: ${{ secrets.MOBY_EMAIL }}
  MOBY_PASSWORD: ${{ secrets.MOBY_PASSWORD }}
  RAY_EMAIL: ${{ secrets.RAY_EMAIL }}
  RAY_PASSWORD: ${{ secrets.RAY_PASSWORD }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: production
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm run build

      - name: Tests coverage
        run: pnpm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}