# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
  COGNITO_USER_EMAIL: ${{ secrets.COGNITO_USER_EMAIL }}
  COGNITO_USER_EMAIL_ADMIN: ${{ secrets.COGNITO_USER_EMAIL_ADMIN }}
  COGNITO_USER_PASSWORD: ${{ secrets.COGNITO_USER_PASSWORD }}
  COGNITO_USER_PASSWORD_ADMIN: ${{ secrets.COGNITO_USER_PASSWORD_ADMIN }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: production
    strategy:
      matrix:
        node-version: [18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: lerna exec npm ci

      - name: Build
        run: npm run build

      - name: Tests coverage
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
